config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "homes#top"
  resources :notepads
  resources :goals
  resources :goal_times
  resources :words
  resources :users, only: [:show, :edit, :update]

  get '/about' => 'homes#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/goal.rb
class Goal < ApplicationRecord
  validates :name, presence: true
  validates :future, presence: true
  validates :now, presence: true
  validates :past, presence: true
  validates :start_date, presence: true
  validates :finish_date, presence: true
  validates :study_time, presence: true
end

app/models/goal_time.rb
class GoalTime < ApplicationRecord
end

app/models/notepad.rb
class Notepad < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :user
  has_many :words, dependent: :destroy
end

app/models/word.rb
class Word < ApplicationRecord
  enum genre: { relationship: 0, learn: 1, life: 2 }

  belongs_to :user, optional: true
end

app/controllers/goal_times_controller.rb
class GoalTimesController < ApplicationController
  def new
    @goals = Goal.all
  end

  def create
    goaltime = GoalTime.new(goaltime_params)
    goaltime.save
    redirect_to action: :index
  end

  def index
  end

  def edit
  end

  private

  def goaltime_params
    params.require(:goaltime).permit(:goal_id, :member,:start_time, :finish_time, :total, :day)
  end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def new
    @goal = Goal.new
  end

  def create
    @goal = Goal.new(goal_params)
    if @goal.save
      redirect_to action: :index
    else
      render :new
    end
  end


  def index
    @goals = Goal.all
  end

  def show
    @goal = Goal.find(params[:id])
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    goal = Goal.find(params[:id])
    goal.update(goal_params)
    redirect_to goal_path(goal.id)
  end

  def destroy
    goal = Goal.find(params[:id])
    goal.destroy
    redirect_to '/goals'
  end

  private

  def goal_params
    params.require(:goal).permit(:name, :future, :now, :past, :start_date, :finish_date, :study_time)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/notepads_controller.rb
class NotepadsController < ApplicationController
  def new
    @notepad = Notepad.new
  end

  def create
    @notepad = Notepad.new(notepad_params)
    if @notepad.save
      redirect_to action: :index
    else
      render :new
    end
  end

  def index
    @notepads = Notepad.all
  end

  def show
    @notepad = Notepad.find(params[:id])
  end

  def edit
    @notepad = Notepad.find(params[:id])
  end

  def update
    notepad = Notepad.find(params[:id])
    notepad.update(notepad_params)
    redirect_to notepad_path(notepad.id)
  end

  def destroy
    notepad = Notepad.find(params[:id])
    notepad.destroy
    redirect_to action: :index
  end

  private

  def notepad_params
    params.require(:notepad).permit(:title, :content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def new
    @word = Word.new
  end

  def create
    @word = Word.new(word_params)
    @word.user_id = current_user.id
    @word.save
    redirect_to action: :index
  end

  def index
    @words = Word.all
  end
  
  def show
    @word = Word.find(params[:id])
  end

  def destroy
    @word = Word.find(params[:id])
    @word.destroy
    redirect_to action: :index
  end

  private

  def word_params
    params.require(:word).permit(:genre, :content, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/goal_times_helper.rb
module GoalTimesHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/notepads_helper.rb
module NotepadsHelper
end

app/helpers/show_helper.rb
module ShowHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/goal_times/edit.html.erb
<h1>GoalTimes#edit</h1>
<p>Find me in app/views/goal_times/edit.html.erb</p>

app/views/goal_times/index.html.erb
<h1>GoalTimes#index</h1>
<p>Find me in app/views/goal_times/index.html.erb</p>

app/views/goal_times/new.html.erb
<h1>新規投稿</h1>
<%= form_with model: GoalTime.new do |f| %>
  <h4>タイトル</h4>
  <%= f.collection_select(:goal_id, @goals, :id, :name) %>

　<%= f.hidden_field :member_id, value: "値" %>
  <h4>本文</h4>
  <%= f.datetime_field :start_time %>
  <%= f.datetime_field :finish_time %>

  <%= f.hidden_field :total, value: "値" %>
  <%= f.hidden_field :day, value: "値" %>

  <%= f.submit '投稿' %>

<% end %>

app/views/goals/edit.html.erb
<h1>編集画面</h1>

<%= form_with model: @goal, url: update_goal_path(@goal.id), method: :patch do |f| %>

<h4>目標</h4>
  <%= f.text_field :name %>

  <h4>理由</h4>
  <h5>未来</h5>
  <%= f.text_area :future %>
  <h5>現在</h5>
  <%= f.text_area :now %>
  <h5>過去</h5>
  <%= f.text_area :past %>

  <h4>期間</h4>
  <%= f.date_field :start_date %>
  <%= f.date_field :finish_date %>
　<h4>期間内勉強時間</h4>
　<%= f.number_field :study_time %>

  <%= f.submit '投稿' %>

<% end %>

app/views/goals/index.html.erb
<h1>目標一覧</h1>
<% @goals.each do |goal| %>

  <p>目標</p>
  <span>
    <%= link_to goal.name, goal_path(goal.id) %>
  </span>
<% end %>

app/views/goals/new.html.erb
<h1>目標投稿</h1>
<% if @goal.errors.any? %>
  <%= @goal.errors.count %>件のエラーが発生しました
  <ul>
    <% @goal.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @goal, url: '/goals', method: :post do |f| %>
  <h4>目標</h4>
  <%= f.text_field :name %>

  <h4>理由</h4>
  <h5>未来</h5>
  <%= f.text_area :future %>
  <h5>現在</h5>
  <%= f.text_area :now %>
  <h5>過去</h5>
  <%= f.text_area :past %>

  <h4>期間</h4>
  <%= f.date_field :start_date %>
  <%= f.date_field :finish_date %>
　<h4>期間内勉強時間</h4>
　<%= f.number_field :study_time %>

  <%= f.submit '投稿' %>
<% end %>

app/views/goals/show.html.erb
<h4>目標</h4>
<p><%= @goal.name %></p>

<h4>理由</h4>
<h5>未来</h5>
<p><%= @goal.future %></p>
<h5>現在</h5>
<p><%= @goal.now %></p>
<h5>過去</h5>
<p><%= @goal.past %></p>

<h4>期間</h4>
<p><%= @goal.start_date %></p>
<p><%= @goal.finish_date %></p>
<h4>期間内勉強時間</h4>
<p><%= @goal.study_time %></p>
<%= link_to "編集", edit_goal_path(@goal.id) %>
<%= link_to "削除", goal_path(@goal.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>

app/views/notepads/edit.html.erb
<h1>編集画面</h1>
<%= form_with model: @notepad, url: notepad_path(@notepad.id), method: :patch do |f| %>
 <h4>タイトル</h4>
 <%= f.text_field :title %>

 <h4>本文</h4>
 <%= f.text_area :content %>

 <%= f.submit '保存' %>
<% end %>

app/views/notepads/index.html.erb
<h1>メモ一覧</h1>

<% @notepads.each do |notepad| %>
 <p>タイトル</p>
 <span>
  <%= link_to notepad.title, notepad_path(notepad.id) %>
 </span>
<% end %>

app/views/notepads/new.html.erb
<h1>新規投稿</h1>
<% if @notepad.errors.any? %>
  <%= @notepad.errors.count %>件のエラーが発生しました
  <ul>
    <% @notepad.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @notepad, url: '/notepads', method: :post do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>

  <h4>本文</h4>
  <%= f.text_area :content %>

  <%= f.submit '投稿' %>
<% end %>

app/views/notepads/show.html.erb
<h2>タイトル</h2>
<p><%= @notepad.title %></p>

<h2>本文</h2>
<p><%= @notepad.content %></p>
<%= link_to "編集", edit_notepad_path(@notepad.id) %>
<%= link_to "削除", notepad_path(@notepad.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>

app/views/users/edit.html.erb
<h2>プロフィール編集</h2>
<%= form_with model: @User do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>

  <%= f.submit "変更を保存" %>
<% end %>

app/views/users/show.html.erb
<div>
  <h3><%= @user.name %></h3>
  <p><%= link_to "プロフィール編集", edit_user_path(@user) %></p>
</div>

app/views/words/index.html.erb
<h1>一覧画面</h1>
<% @words.each do |word| %>
<div>
  <p>ジャンル : <%= word.genre %></p>
  <p>ユーザーネーム：<%= link_to word.user.name, word_path(word.id) %></p>
  <p>名言：<%= word.content %></p>
  <p>作成者：<%= word.name %></p>
</div>
<% end %>

app/views/words/new.html.erb
<h1>新規投稿</h1>
<%= form_with model: Word.new do |f| %>
  <h4>ジャンル選択</h4>
  <%= f.select :genre, Word.genres_i18n.invert, {}, class: 'form-control' %>

  <h4>名言</h4>
  <%= f.text_area :content %>
  <h4>名前</h4>
  <%= f.text_field :name %>

  <%= f.submit '投稿' %>
<% end %>

app/views/words/show.html.erb
<div>
  <p>ジャンル : <%= @word.genre %></p>
  <p>ユーザーネーム：<%= @word.user.name %></p>
  <p>名言：<%= @word.content %></p>
  <p>作成者：<%= @word.name %></p>
  <p>投稿日：<%= @word.created_at.strftime('%Y/%m/%d') %></p>
  <% if @word.user == current_user %>
    <%= link_to "削除", word_path(@word), method: :delete %>
  <% end %>
</div>